### ISSUE TITLE
Assert triggers in 4.0b1 and causes crash

### ISSUE THREAD

**Issue by erict-powersoft** [melinsoftware/meos#74] opened 2024-03-27 17:14 UTC
Assert is oeventSQL.cpp:616, out contains one item about a class.  Crashes every time I open the event, which was created with 4b1, then uploaded to database.  Can't remember if I created the class after or before I uploaded.  This is the database contents of oclass:
Id,Name,Course,MultiCourse,LegMethod,ExtId,LongName,LowAge,HighAge,HasPool,AllowQuickEntry,ClassType,Sex,StartName,StartBlock,NoTiming,FreeStart,RequestStart,IgnoreStart,FirstStart,StartInterval,Vacant,Reserved,ClassFee,HighClassFee,SecondHighClassFee,ClassFeeRed,HighClassFeeRed,SecondHighClassFeeRed,SortIndex,MaxTime,Status,DirectResult,Bib,BibMode,Unordered,Heat,Locked,Qualification,NumberMaps,Result,TransferFlags,SplitPrint,DataA,DataB,TextA,Modified,Counter,Removed
1,SomeClass,0,,,0,,0,0,0,0,Adult,,Start 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,,0,,,0,0,0,,0,,1,,0,0,,2024-03-27 13:00:22,5,0
Interestingly, when single-stepping through, in oEvent::msSynchronize line 88 returns 2 [I see it means opStatusOK], and it doesn't really do anything other than that, therefore the assert fails.

**Comment by erict-powersoft** [comment] 2024-03-27 17:26
I found a kind of work around: by putting a breakpoint on line 616, and if out is not empty, then move the yellow arrow one line up so that it reruns checkChanged.  The second time through the function it will not complain about the class and out will be empty.

**Comment by erikmelin** [comment] 2024-04-05 07:30
There is an issue with the class (possibly using uninitialized memory), so I suspect there could be crashes as well. This will be fixed, but I'll keep this open for now, since it is hard to verify for me without a "proper" repeat.

**Comment by erikmelin** [comment] 2024-04-07 07:21
@erict-powersoft I have now published RC1. Please check if you can still reproduce the problem.

**Closed** 2024-05-03 18:28 UTC
